[tool.poetry]
name = "invesalius3_nix_develop"
version = "0.1.0"
description = ""
authors = ["Thiago Franco de Moraes <totonixsame@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
Cython = "^0.29.32"
Pillow = "^9.3.0"
PyPubSub = "^4.0.3"
configparser = "^5.0.1"
h5py = "^3.7.0"
imageio = "^2.22.0"
nibabel = "^4.0.2"
numpy = "^1.23.5"
psutil = "^5.8.0"
pyserial = "^3.5"
python-gdcm = "^3.0.20"
scikit-image = "^0.19.3"
scipy = "^1.9.1"
vtk = "^9.2.0"
wxPython = "^4.2.0"
torch = "^1.12.1"
pyacvd = "^0.2.7"

[tool.poetry.dev-dependencies]
ipython = "^8.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
