[tool.poetry]
name = "invesalius3_nix_develop"
version = "0.1.0"
description = ""
authors = ["Thiago Franco de Moraes <totonixsame@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
Cython = "0.29.28"
Pillow = "9.1.1"
PyPubSub = "4.0.3"
configparser = "5.0.1"
h5py = "2.10.0"
imageio = "2.9.0"
nibabel = "3.2.1"
numpy = "1.22.1"
plaidml-keras = "0.7.0"
psutil = "5.8.0"
pyserial = "3.5"
python-gdcm = "3.0.12"
scikit-image = "0.19.1"
scipy = "1.7.3"
vtk = "9.1.0"
wxPython = "4.2.0"
torch = "^1.12.1"
pyacvd = "0.2.7"
scikit-build = "^0.15.0"

[tool.poetry.dev-dependencies]
ipython = "^8.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
